export const FIND_ALL_COMUNAS_FETCH_REQUESTED =
  'FIND_ALL_COMUNAS_FETCH_REQUESTED';
export const FIND_ALL_COMUNAS_FETCH_SUCCEEDED =
  'FIND_ALL_COMUNAS_FETCH_SUCCEEDED';
export const FIND_ALL_COMUNAS_FETCH_FAILED = 'FIND_ALL_COMUNAS_FETCH_FAILED';

export const FIND_COURIERS_FETCH_REQUESTED = 'FIND_COURIERS_FETCH_REQUESTED';
export const FIND_COURIERS_FETCH_SUCCEEDED = 'FIND_COURIERS_FETCH_SUCCEEDED';
export const FIND_COURIERS_FETCH_FAILED = 'FIND_COURIERS_FETCH_FAILED';
